name: cargo fmt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Formats all bin and lib files of the current crate using rustfmt
      run: |
        cargo fmt --all -- --check
