name: cargo generate-lockfile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Generate the lockfile for a package
      run: |
        cargo generate-lockfile --locked
