name: cargo generate-lockfile
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1

    - name: Generate the lockfile for a package
      run: |
        cargo generate-lockfile --locked
